name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-api-key-source: nuget.org

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: msbuild -p:Configuration=Release

      - name: Pack
        run: nuget pack DotnetRuntimeBootstrapper.nuspec

      - name: Deploy
        run: nuget push DotnetRuntimeBootstrapper.nupkg